### ISSUE TITLE
Form registro

### ISSUE THREAD

**Issue by NicoGonzalez1294** [santinohamada/ProyectoFinal#59]
Al momento de registrar un nuevo usuario no se deberia poder colocar numeros y letras en el nombre y apellido.
![Captura de pantalla 2024-11-12 143711](https://github.com/user-attachments/assets/155c9b48-c85e-43ca-aeeb-2834faff2cfc)
![Captura de pantalla 2024-11-12 143744](https://github.com/user-attachments/assets/967a85aa-7806-47d8-a9bd-80bb2241f524)
Cualquier cosita pueden contactarme por el slack de RollingCode

**Comment by santinohamada** [comment]
Se solucionó el issue añadiendo expresiones regulares que validen el formato de entrada de Nombre y Apellido
